version: '3.8'

services:
  scraper:
    build: .
    container_name: real_estate_scraper
    environment:
      - PYTHONUNBUFFERED=1  # Helpful for real-time logging
    restart: unless-stopped
    networks:
      - my_network
    # Simple loop structure as a basic scheduler to run daily
    entrypoint: ["sh", "-c", "while true; do python app/main.py; sleep 86400; done"]

networks:
  my_network:
    driver: bridge
